kind: ConfigMap
apiVersion: v1
metadata:
  name: boathouse-vault-agent-config
  labels:
    app.kubernetes.io/name: boathouse
    app.kubernetes.io/instance: boathouse
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "boathouse"
        }
        "type" = "kubernetes"
        "mount_path" = "auth/k8s-cancentral-02-covid-aks"
      }
    }
    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"
    cache {
      "use_auto_auth_token" = "force"
    }
    listener "tcp" {
      address = "127.0.0.1:8100"
      "tls_disable" = true
    }
    "vault" = {
      "address" = "https://vault.covid.cloud.statcan.ca"
    }
